---
language: node_js
node_js: 10

before_script:
  - npm install markdownlint-cli
script:
  - markdownlint -c .markdownlint.json workshop --ignore workshop/SUMMARY.md
  - ./.verify-links.sh -v workshop
